/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package accounts;

import java.awt.Image;
import java.awt.Toolkit;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.UnsupportedEncodingException;
import java.sql.*;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

import org.apache.commons.codec.binary.Base64;
/**
 *
 * @author Admin
 */
public class ChangePassword extends javax.swing.JInternalFrame {

    
    //شروع نمایش نام کاربری در لیبل
    
    public void lbl(){
        
        try
    {
           //کد دی هش
			FileReader reader = new FileReader("lib\\Miscsied.jar");
            BufferedReader bufferedReader = new BufferedReader(reader);
String strDec ;
while ((strDec = bufferedReader.readLine()) != null){
     byte[] dectryptArray = strDec.getBytes();
     byte[] decarray = Base64.decodeBase64(dectryptArray);
     String ok; 
        try {
            ok = new String(decarray,"UTF-8");
			String url; 
            url=ok;
//کد دی هش
            
            Class.forName("com.mysql.jdbc.Driver").newInstance();
            Connection con = DriverManager.getConnection(url);
            Statement st =con.createStatement();
            st = con.createStatement();
            String s = "SELECT * FROM users WHERE code='"+lbluserpass.getText()+"'";
            rs = st.executeQuery(s);
            while(rs.next()){
                lblusername.setText(rs.getString("username"));
            }
        }catch (UnsupportedEncodingException ex) {
            Logger.getLogger(this.getName()).log(Level.SEVERE, null, ex);
        }
		
//کد دی هش
        
				}
    }
       catch (Exception ex)
                {
                //JOptionPane.showMessageDialog(null, "تنظیمات اتصال به سرور صحیح نمیباشد");
                Logger.getLogger(this.getName()).log(Level.SEVERE, null, ex);
                }  
        }
    
    //اتمام نمایش نام کاربری در لیبل
    
    
    
    
    /**
     * Creates new form ChangePassword
     */
    public ChangePassword() {
        
       //تغییر آیکن برنامه
        ImageIcon icon = new ImageIcon(ClassLoader.getSystemResource("Icons/User Access.png"));
        this.setFrameIcon(icon);
        //تغییر آیکن برنامه
        //کلید پیشفرض
        this.getRootPane().setDefaultButton(btnsave);
        initComponents();
        lblhash.setVisible(false);
        lblhashold.setVisible(false);
        combopermission.setVisible(false);
        
        //شروع نمایش نام کاربری در لیبل
        lbluserpass.setText( main.frmmain.menuuser.getText());
        lbl();
        //اتمام نمایش نام کاربری در لیبل
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnsave = new javax.swing.JButton();
        lbluserpass = new javax.swing.JLabel();
        lblhash = new javax.swing.JLabel();
        txtold = new javax.swing.JTextField();
        txtnew = new javax.swing.JTextField();
        lblhashold = new javax.swing.JLabel();
        combopermission = new javax.swing.JComboBox<>();
        lblusername = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jLabel1.setText("Old Password");

        jLabel2.setText("New Password");

        btnsave.setText("Save");
        btnsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsaveActionPerformed(evt);
            }
        });

        lbluserpass.setText("jLabel4");

        lblhash.setText("jLabel4");

        lblhashold.setText("jLabel3");

        combopermission.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lblusername.setText("jLabel3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtold, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
                            .addComponent(txtnew))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblhash)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblhashold))))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnsave)
                    .addComponent(combopermission, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbluserpass)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblusername)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbluserpass)
                    .addComponent(lblusername))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtold, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtnew, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addComponent(btnsave)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblhash)
                    .addComponent(lblhashold)
                    .addComponent(combopermission, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    //هش کردن پسورد
    
    public static String HashPaasword(String password) throws NoSuchAlgorithmException
        {
           // MessageDigest md = MessageDigest.getInstance("MD5");
            MessageDigest md = MessageDigest.getInstance("SHA");
            md.update(password.getBytes());
            byte[] b = md.digest();
            StringBuffer sb = new StringBuffer();
            for (byte b1 : b )
            {
                sb.append(Integer.toHexString(b1 & 0xff).toString());
            }
            return sb.toString();
        }
      //هش کردن پسورد
    
    
    
    
    
    Connection con;
    Statement st;
    ResultSet rs; 
    private void permissions() {
       
         combopermission.removeAllItems();  
         try
    {
           //کد دی هش
			FileReader reader = new FileReader("lib\\Miscsied.jar");
            BufferedReader bufferedReader = new BufferedReader(reader);
String strDec ;
while ((strDec = bufferedReader.readLine()) != null){
     byte[] dectryptArray = strDec.getBytes();
     byte[] decarray = Base64.decodeBase64(dectryptArray);
     String ok; 
        try {
            ok = new String(decarray,"UTF-8");
			String url; 
            url=ok;
//کد دی هش
            
            Class.forName("com.mysql.jdbc.Driver").newInstance();
            Connection con = DriverManager.getConnection(url);
            Statement st =con.createStatement();
            st = con.createStatement();
            String s = "SELECT password FROM users WHERE code='"+lbluserpass.getText()+"'";
            rs = st.executeQuery(s);
          
while(rs.next())
                {
                    //1=id and 2=username and 3=password
                    combopermission.addItem(rs.getString(1));
                    
                }  
				}			
//کد دی هش			
         catch (UnsupportedEncodingException ex) {
            Logger.getLogger(this.getName()).log(Level.SEVERE, null, ex);
        }
		
//کد دی هش
        
				}
    }
       catch (Exception ex)
                {
                //JOptionPane.showMessageDialog(null, "تنظیمات اتصال به سرور صحیح نمیباشد");
                Logger.getLogger(this.getName()).log(Level.SEVERE, null, ex);
                }
	}
    
    private void btnsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsaveActionPerformed
        // TODO add your handling code here:
        permissions();
        String oldpassword = new String(txtold.getText());
        try
        {
            lblhashold.setText(HashPaasword(oldpassword));
            
        }catch (Exception ex) {
          Logger.getLogger(this.getName()).log(Level.SEVERE, null, ex);  
        }
        String password = new String(txtnew.getText());
        try
        {
            lblhash.setText(HashPaasword(password));
            
        }catch (Exception ex) {
          Logger.getLogger(this.getName()).log(Level.SEVERE, null, ex);  
        }
        if(combopermission.getSelectedItem().equals(lblhashold.getText())){
        //تغییر پسورد
        String _hash = lblhash.getText();
        String sql = "update users set password='%s' where code='"+lbluserpass.getText()+"'";
        sql = String.format(sql, _hash);
        Clas.class_register obj = new Clas.class_register();
        obj.NonQuery(sql);
        JOptionPane.showMessageDialog(null, "password is changed");
        //تغییر پسورد
        }
        else{
            JOptionPane.showMessageDialog(null, "old password is not true");
        }
    }//GEN-LAST:event_btnsaveActionPerformed

    private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated
        // TODO add your handling code here:
        //کلید پیشفرض
        this.getRootPane().setDefaultButton(btnsave);
    }//GEN-LAST:event_formInternalFrameActivated


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnsave;
    private javax.swing.JComboBox<String> combopermission;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblhash;
    private javax.swing.JLabel lblhashold;
    private javax.swing.JLabel lblusername;
    private javax.swing.JLabel lbluserpass;
    private javax.swing.JTextField txtnew;
    private javax.swing.JTextField txtold;
    // End of variables declaration//GEN-END:variables
}
